version: '3.5'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test

  bot:
    image: krip_bot:latest
    environment:
      CREATE_TABLE: "yes"
      DB_SWITCH: "on"
      TOKEN: 6016827182:AAHwgjaXoYmXTgHWPbrY6cHdue4j2vsvFpY
      HOST: db
      PORT: 5432
      USER: postgres
      PASSWORD: test
      DBNAME: postgres
      SSLMODE: disable